name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Open Source (SCA) scan
        run: snyk test --severity-threshold=high || true

      - name: Run Snyk Code (SAST) scan
        run: snyk code test --severity-threshold=high || true
